import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, mkdir, writeFile, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { randomUUID } from "node:crypto";
import { createServer } from "node:http";
import { AvatarService } from "../../apps/server/src/avatar-service.ts";
import { AvatarStore } from "../../apps/server/src/avatar-store.ts";
test("role settings persist; soft deletion hides every API and survives stale saves and legacy import",async t=>{
  const root=await mkdtemp(join(tmpdir(),"avatar-management-"));
  const service=new AvatarService(root,async()=>{});await service.initialized;
  const id=randomUUID(),batch=randomUUID(),source=join(root,id,"upload.bin");
  await mkdir(join(root,id),{recursive:true});await writeFile(source,"original remains");
  service.store.addBatch(batch,batch);service.store.save({id,batchId:batch,name:"before",status:"ready",stage:"ready",percent:100,createdAt:new Date().toISOString(),sourcePath:source,assetPath:join(root,id),attempt:0});
  const stale=service.store.get(id)!;
  const server=createServer((req,res)=>void service.handle(req,res));await new Promise<void>(r=>server.listen(0,"127.0.0.1",r));
  const url=`http://127.0.0.1:${(server.address() as {port:number}).port}/api/avatars`;
  const headers={"x-avatar-upload":"1","content-type":"application/json"};
  const edit=(data:unknown)=>fetch(`${url}/${id}`,{method:"PATCH",headers,body:JSON.stringify(data)});
  t.after(async()=>{await service.dispose();server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));await rm(root,{recursive:true,force:true});});
  assert.equal((await edit({name:"新名字",persona:"我是你的老师，耐心简短"})).status,200);
  assert.equal((await edit({name:" "})).status,400);
  assert.equal((await edit({persona:"x".repeat(2001)})).status,400);
  assert.equal((await edit({DELET_OR_NOT:false})).status,400);
  assert.equal((await fetch(`${url}/${id}`,{method:"DELETE"})).status,403);
  await service.acquireCall(id,"active",new AbortController().signal);
  assert.equal((await fetch(`${url}/${id}`,{method:"DELETE",headers})).status,409);service.releaseCall("active");
  assert.equal((await fetch(`${url}/${id}`,{method:"DELETE",headers})).status,200);
  assert.equal(service.store.db.prepare("SELECT DELET_OR_NOT FROM avatars WHERE id=?").get(id)?.DELET_OR_NOT,1);
  assert.equal(service.store.get(id)?.persona,"我是你的老师，耐心简短");
  assert.equal(service.store.get(id)?.name,"新名字");
  const persisted=new AvatarStore(root);assert.equal(persisted.get(id)?.name,"新名字");assert.equal(persisted.get(id)?.persona,"我是你的老师，耐心简短");persisted.close();
  assert.equal((await (await fetch(url)).json()).avatars.length,0);
  for(const path of ["status","source.jpg","frame.html"])assert.equal((await fetch(`${url}/${id}/${path}`)).status,404);
  assert.equal((await fetch(`${url}/${id}/retry`,{method:"POST",headers})).status,404);
  await assert.rejects(service.acquireCall(id,"archived-call",new AbortController().signal));
  // Stale worker data may change stage but must not undo the archive marker.
  service.store.save({...stale,status:"ready"});assert.equal(service.store.list().length,0);
  assert.equal(await readFile(source,"utf8"),"original remains");
  const reopened=new AvatarStore(root);await reopened.importLegacy();
  assert.equal(reopened.list().length,0);assert.equal(reopened.list(true).length,1);reopened.close();
});
test("editing a running worker survives progress; archiving stops it without replay",async t=>{
  const root=await mkdtemp(join(tmpdir(),"avatar-management-running-"));let progress:((s:string,p:number)=>void)|undefined;let starts=0;
  const service=new AvatarService(root,async(_dir,_id,report,signal)=>{
    starts++;progress=report;await new Promise<void>((_r,reject)=>signal.addEventListener("abort",()=>reject(signal.reason),{once:true}));
  });await service.initialized;
  const server=createServer((req,res)=>void service.handle(req,res));await new Promise<void>(r=>server.listen(0,"127.0.0.1",r));
  const base=`http://127.0.0.1:${(server.address() as {port:number}).port}/api/avatars`,headers={"x-avatar-upload":"1","content-type":"application/json"};
  t.after(async()=>{await service.dispose();server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));await rm(root,{recursive:true,force:true});});
  const data=await (await fetch(base+"/batches",{method:"POST",headers,body:JSON.stringify({requestId:randomUUID(),files:[{name:"test.png",type:"image/png",data:Buffer.from([137,80,78,71,13,10,26,10,0]).toString("base64")}]})})).json();
  const id=data.avatars[0].id;
  for(let i=0;i<100&&!progress;i++)await new Promise(r=>setTimeout(r,10));assert.ok(progress);
  assert.equal((await fetch(base+"/"+id,{method:"PATCH",headers,body:JSON.stringify({name:"changed",persona:"patient teacher"})})).status,200);
  progress("video",40);assert.equal(service.store.get(id)?.name,"changed");
  assert.equal((await fetch(base+"/"+id,{method:"DELETE",headers})).status,200);
  await new Promise(r=>setTimeout(r,50));assert.equal(service.store.list().length,0);assert.equal(starts,1);
  assert.equal(service.store.get(id)?.persona,"patient teacher");assert.ok(await readFile(service.store.get(id)!.sourcePath));
});
